'use strict';
const path=require('node:path');
const AUDIO_SCHEMA_VERSION=1;const RIGHTS=Object.freeze(['user-owned','user-licensed','original-recording','unknown-review-required']);const SOURCE_TYPES=Object.freeze(['imported-audio','voiceover']);const MAX_SOURCES=100,MAX_ITEMS=300;
function clone(v){return structuredClone(v);}function finite(v){return typeof v==='number'&&Number.isFinite(v);}function inside(file,root){const rel=path.relative(path.resolve(root),path.resolve(file));return rel===''||(!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel));}
function source(input,index){if(!input||typeof input!=='object')throw new TypeError('audio source is invalid.');if(!SOURCE_TYPES.includes(input.type))throw new TypeError('audio source type is invalid.');if(!RIGHTS.includes(input.rights))throw new TypeError('audio rights status is invalid.');if(typeof input.assetId!=='string'||!input.assetId||input.assetId.length>128)throw new TypeError('audio asset id is invalid.');return{id:input.id||`audio-source-${index+1}`,assetId:input.assetId,type:input.type,rights:input.rights,label:typeof input.label==='string'?input.label.slice(0,160):'',provenance:input.provenance||'user-import'};}
function item(input,index,{durationSeconds,sources}){if(!input||typeof input!=='object'||!sources.has(input.sourceId))throw new TypeError('audio item source is invalid.');const start=input.startSeconds??0,end=input.endSeconds;if(!finite(start)||!finite(end)||start<0||end<=start||end>durationSeconds+1e-6)throw new TypeError('audio timing is invalid.');const sourceStart=input.sourceStartSeconds??0;if(!finite(sourceStart)||sourceStart<0)throw new TypeError('audio source trim is invalid.');const gain=input.gainDb??0;if(!finite(gain)||gain<-60||gain>12)throw new TypeError('audio gain is invalid.');const fadeIn=input.fadeInSeconds??0,fadeOut=input.fadeOutSeconds??0;if(!finite(fadeIn)||!finite(fadeOut)||fadeIn<0||fadeOut<0||fadeIn>end-start||fadeOut>end-start)throw new TypeError('audio fade is invalid.');return{id:input.id||`audio-item-${index+1}`,sourceId:input.sourceId,startSeconds:start,endSeconds:end,sourceStartSeconds:sourceStart,gainDb:gain,fadeInSeconds:fadeIn,fadeOutSeconds:fadeOut,mute:input.mute===true,solo:input.solo===true};}
function createAudioModel({durationSeconds,sources=[],items=[],clipAudio={}}={}){const src=sources.map(source),map=new Map(src.map(s=>[s.id,s]));const model={schemaVersion:AUDIO_SCHEMA_VERSION,revision:0,sources:src,items:items.map((x,i)=>item(x,i,{durationSeconds,sources:map})),clipAudio:clone(clipAudio)};validateAudioModel(model,{durationSeconds});return model;}
function validateAudioModel(model,{durationSeconds}={}){if(!model||model.schemaVersion!==AUDIO_SCHEMA_VERSION||!Number.isSafeInteger(model.revision)||model.revision<0||!Array.isArray(model.sources)||model.sources.length>MAX_SOURCES||!Array.isArray(model.items)||model.items.length>MAX_ITEMS)throw new TypeError('audio model is invalid.');const ids=new Set(),src=new Map();model.sources.forEach((s,i)=>{const n=source(s,i);if(ids.has(n.id))throw new TypeError('audio source IDs must be unique.');ids.add(n.id);src.set(n.id,n);});const itemIds=new Set();model.items.forEach((x,i)=>{const n=item(x,i,{durationSeconds,sources:src});if(itemIds.has(n.id))throw new TypeError('audio item IDs must be unique.');itemIds.add(n.id);});if(!model.clipAudio||typeof model.clipAudio!=='object'||Array.isArray(model.clipAudio))throw new TypeError('clip audio settings are invalid.');for(const [clipId,value] of Object.entries(model.clipAudio)){if(!clipId||!value||!['keep','mute'].includes(value.mode))throw new TypeError('clip audio mode is invalid.');if(value.gainDb!==undefined&&(!finite(value.gainDb)||value.gainDb<-60||value.gainDb>12))throw new TypeError('clip audio gain is invalid.');}return model;}
function editAudioModel(model,operation,{expectedRevision,durationSeconds}={}){validateAudioModel(model,{durationSeconds});if(model.revision!==expectedRevision)throw Object.assign(new Error('audio revision conflict.'),{code:'AUDIO_CONFLICT'});const next=clone(model);if(operation.type==='set-clip')next.clipAudio[operation.clipId]={mode:operation.mode,gainDb:operation.gainDb??0};else if(operation.type==='remove-item')next.items=next.items.filter(x=>x.id!==operation.id);else if(operation.type==='add-source')next.sources.push(source(operation.source,next.sources.length));else if(operation.type==='add-item'){const map=new Map(next.sources.map(s=>[s.id,s]));next.items.push(item(operation.item,next.items.length,{durationSeconds,sources:map}));}else throw new TypeError('unsupported audio operation.');next.revision++;validateAudioModel(next,{durationSeconds});return next;}
function rightsReviewRequired(model){return model.sources.some(s=>s.rights==='unknown-review-required');}
function withAudio(plan,model,{audioResolver,trustedRoots=[]}={}){validateAudioModel(model,{durationSeconds:plan.durationSeconds});if(typeof audioResolver!=='function')throw new TypeError('audioResolver is required.');const solos=new Set(model.items.filter(x=>x.solo&&!x.mute).map(x=>x.id));const standalone=model.items.filter(x=>!x.mute&&(solos.size===0||solos.has(x.id))).map((x,index)=>{const src=model.sources.find(s=>s.id===x.sourceId),resolved=audioResolver(src.assetId);if(typeof resolved!=='string'||!path.isAbsolute(resolved)||/^[a-z][a-z0-9+.-]*:\/\//i.test(resolved)||!trustedRoots.some(r=>inside(resolved,r)))throw new TypeError('audio path is not a trusted local path.');return{index,sourceId:src.id,assetId:src.assetId,rights:src.rights,sourcePath:path.resolve(resolved),startSeconds:x.startSeconds,durationSeconds:x.endSeconds-x.startSeconds,sourceStartSeconds:x.sourceStartSeconds,gainDb:x.gainDb,fadeInSeconds:x.fadeInSeconds,fadeOutSeconds:x.fadeOutSeconds};});return{...clone(plan),audioMix:{standalone,clipAudio:clone(model.clipAudio),rightsReviewRequired:rightsReviewRequired(model)}};}
function noTrendingAudioDownloadCapability(){return true;}
module.exports={AUDIO_SCHEMA_VERSION,RIGHTS,SOURCE_TYPES,createAudioModel,editAudioModel,noTrendingAudioDownloadCapability,rightsReviewRequired,validateAudioModel,withAudio};
