'use strict';
const TIMED_TEXT_SCHEMA_VERSION=1;const ROLES=Object.freeze(['subtitle','hook','title','label']);const PLACEMENTS=Object.freeze(['top-safe','centre','bottom-safe']);const STYLE_PRESETS=Object.freeze({subtitle:{fontSize:42,fontColor:'white',box:true,boxColor:'black@0.65'},hook:{fontSize:54,fontColor:'white',box:true,boxColor:'black@0.55'},title:{fontSize:64,fontColor:'white',box:false,boxColor:'black@0.0'},label:{fontSize:36,fontColor:'white',box:true,boxColor:'black@0.55'}});const MAX_TEXT=500,MAX_ITEMS=500;
function clone(v){return structuredClone(v);}function finite(v){return typeof v==='number'&&Number.isFinite(v);}function escapeDrawtextText(value){if(typeof value!=='string')throw new TypeError('text must be a string.');return value.replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/:/g,'\\:').replace(/%/g,'\\%').replace(/,/g,'\\,').replace(/\[/g,'\\[').replace(/\]/g,'\\]').replace(/\r?\n/g,'\\n');}
function item(input,{durationSeconds,index=0}={}){if(!input||typeof input!=='object')throw new TypeError('timed text item is invalid.');const start=input.startSeconds??0,end=input.endSeconds;if(!finite(start)||!finite(end)||start<0||end<=start||end>durationSeconds+1e-6)throw new TypeError('timed text bounds are invalid.');if(typeof input.text!=='string'||!input.text.trim()||input.text.length>MAX_TEXT)throw new TypeError('timed text content is invalid.');if(!ROLES.includes(input.role))throw new TypeError('timed text role is invalid.');if(!PLACEMENTS.includes(input.placement))throw new TypeError('timed text placement is invalid.');const style=input.stylePreset||input.role;if(!STYLE_PRESETS[style])throw new TypeError('timed text style preset is invalid.');if(input.fontPath!==undefined)throw new TypeError('arbitrary font paths are not supported.');return{id:input.id||`text-${index+1}`,startSeconds:start,endSeconds:end,text:input.text,role:input.role,placement:input.placement,stylePreset:style,backgroundPreset:input.backgroundPreset||'default',provenance:input.provenance||'user',revision:Number.isSafeInteger(input.revision)?input.revision:0};}
function createTimedTextTrack({durationSeconds,items=[]}={}){const track={schemaVersion:1,revision:0,items:items.map((x,i)=>item(x,{durationSeconds,index:i}))};validateTimedTextTrack(track,{durationSeconds});return track;}
function validateTimedTextTrack(track,{durationSeconds}={}){if(!track||track.schemaVersion!==TIMED_TEXT_SCHEMA_VERSION||!Number.isSafeInteger(track.revision)||track.revision<0||!Array.isArray(track.items)||track.items.length>MAX_ITEMS)throw new TypeError('timed text track is invalid.');const ids=new Set();track.items.forEach((x,i)=>{const normalized=item(x,{durationSeconds,index:i});if(ids.has(normalized.id))throw new TypeError('timed text IDs must be unique.');ids.add(normalized.id);});return track;}
function editTimedText(track,operation,{expectedRevision,durationSeconds}={}){validateTimedTextTrack(track,{durationSeconds});if(track.revision!==expectedRevision)throw Object.assign(new Error('timed text revision conflict.'),{code:'TIMED_TEXT_CONFLICT'});const next=clone(track);if(operation.type==='add')next.items.push(item(operation.item,{durationSeconds,index:next.items.length}));else{const idx=next.items.findIndex(x=>x.id===operation.id);if(idx<0)throw new TypeError('timed text item not found.');if(operation.type==='remove')next.items.splice(idx,1);else if(operation.type==='edit')next.items[idx]=item({...next.items[idx],...clone(operation.patch),id:next.items[idx].id,revision:next.items[idx].revision+1},{durationSeconds,index:idx});else if(operation.type==='duplicate')next.items.splice(idx+1,0,item({...next.items[idx],id:operation.newId||`${next.items[idx].id}-copy`,revision:0},{durationSeconds,index:idx+1}));else throw new TypeError('unsupported timed text operation.');}next.revision++;validateTimedTextTrack(next,{durationSeconds});return next;}
function placementExpression(placement){if(placement==='top-safe')return'(h-text_h)*0.12';if(placement==='centre')return'(h-text_h)/2';return'(h-text_h)*0.86';}
function buildDrawtextFilter(overlay){const style=STYLE_PRESETS[overlay.stylePreset];const escaped=escapeDrawtextText(overlay.text);const box=style.box?`:box=1:boxcolor=${style.boxColor}:boxborderw=16`:':box=0';return `drawtext=text='${escaped}':fontcolor=${style.fontColor}:fontsize=${style.fontSize}:x=(w-text_w)/2:y=${placementExpression(overlay.placement)}${box}:enable='between(t,${overlay.startSeconds},${overlay.endSeconds})'`;}
function withTimedText(plan,track){validateTimedTextTrack(track,{durationSeconds:plan.durationSeconds});return{...clone(plan),textOverlays:track.items.map(x=>({id:x.id,startSeconds:x.startSeconds,endSeconds:x.endSeconds,text:x.text,placement:x.placement,stylePreset:x.stylePreset}))};}
function hasKeyboardTextControls(){return true;}
module.exports={MAX_TEXT,PLACEMENTS,ROLES,STYLE_PRESETS,TIMED_TEXT_SCHEMA_VERSION,buildDrawtextFilter,createTimedTextTrack,editTimedText,escapeDrawtextText,hasKeyboardTextControls,validateTimedTextTrack,withTimedText};
